routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MasterBarangController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\TransaksiPembelianController;
use App\Http\Controllers\PDFController;
use App\Models\TransaksiPembelian;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'home']);
Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
    Route::resource('transaksi', TransaksiPembelianController::class)->only(['store','show', 'create']);
    Route::middleware(['admin'])->group(function (){
        Route::resource('transaksi', TransaksiPembelianController::class)->only(['index']);
        Route::resource('barang', MasterBarangController::class)->except(['edit']);
        Route::resource('pengguna', PenggunaController::class)->except(['show', 'edit']);
    });
    Route::resource('pengguna', PenggunaController::class)->only(['show']);
    Route::get('transaksi/{transaksi_id}/printtransaksi', [PDFController::class, 'printTransaksi'])->name('transaksi.print');
});
require __DIR__ . '/auth.php';

resources/views/transaksi/create.blade.php
@extends('layouts.master')

@section('title')
    Tambah Transaksi | Cashier
@endsection

@section('content')
    <div class="d-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Transaksi</h1>
        <a href="{{ route('dashboard') }}" class="btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-chevron-circle-left fa-sm text-white-50 d-inline-block"></i>
            <div class="d-none d-sm-inline-block">Kembali</div>
        </a>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Tambah Transaksi Baru</h6>
        </div>
        <div class="card-body">
            <form action="{{ route('transaksi.store') }}" method="post">
                @csrf
                <div id="form_field">
                    <div class="row d-flex" id="row1">
                        <div class="col-12 col-md-5">
                            <div class="form-group">
                                <input class="form-control formBarang namaBarang" id="barang1" name="barang[]"
                                    list="nama_barang" placeholder="Pilih barang..." onchange="resetIfInvalid(this);"
                                    autocomplete="off" required>
                                <datalist id="nama_barang">
                                    @foreach ($barang as $item)
                                        <option value="{{ $item->id }} - {{ $item->nama_barang }}"></option>
                                    @endforeach
                                </datalist>
                            </div>
                        </div>
                        <div class="col-8 col-md-2">
                            <div class="form-group">
                                <input type="number" min="0" class="form-control formBarang kuantitas" id="kuantitas1"
                                    name="kuantitas[]" placeholder="Kuantitas" required>
                            </div>
                        </div>
                        <div class="order-4 order-md-3 col-6 col-md-2">
                            <div class="form-group">
                                <input type="number" value="0" class="form-control formBarang" id="harga1"
                                    placeholder="Harga Satuan" readonly>
                            </div>
                        </div>
                        <div class="order-5 order-md-4 col-6 col-md-2">
                            <div class="form-group">
                                <input type="number" value="0" class="form-control formBarang subtotal" id="subtotal1"
                                    placeholder="Subtotal" readonly>
                            </div>
                        </div>
                        <div class="order-3 order-md-5 col-4 col-md-1">
                            <button type="button" id="add" class="btn btn-primary w-100">&plus;
                            </button>
                        </div>

                    </div>
                </div>
                <div class="row d-flex justify-content-end">
                    <div class="col-md-3">
                        <input type="text" id="totalTransaksi" value="0" class="form-control mb-3" placeholder="Total"
                            readonly>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary w-100 mb-3">Tambah Transaksi</button>
            </form>

        </div>
    </div>
@endsection


@push('scripts')
    <script>
        function resetIfInvalid(el) {
            //just for beeing sure that nothing is done if no value selected
            if (el.value == "")
                return;
            var options = el.list.options;
            for (var i = 0; i < options.length; i++) {
                if (el.value == options[i].value)
                    //option matches: work is done
                    return;
            }
            //no match was found: reset the value
            el.value = "";
        }

        var barang = JSON.parse(JSON.stringify(<?php echo $barang; ?>))
        var harga = [];
        for (let i = 0; i < barang.length; i++) {
            index = barang[i]['id'];
            harga[index] = barang[i]['harga_satuan']
        };

        $(document).ready(function() {
            var i = 1;
            var exist = [1];

            function arrayRemove(arr, value) {

                return arr.filter(function(ele) {
                    return ele != value;
                });
            }
            console.log(exist)

            $('#add').click(function() {
                i++
                exist.push(i)
                $('#form_field').append(`<div class="row d-flex" id="row` + i + `">
                    <div class="col-12 col-md-5">
                        <div class="form-group">
                            <input class="form-control formBarang namaBarang" id="barang` + i + `" name="barang[]" list="nama_barang"placeholder="Pilih barang..." onchange="resetIfInvalid(this);" autocomplete="off" required>
                            <datalist id="nama_barang">
                        @foreach ($barang as $item)
                            <option value="{{ $item->id }} - {{ $item->nama_barang }}"></option>
                        @endforeach
                        </datalist>
                    </div>
                    </div>
                    <div class="col-8 col-md-2">
                    <div class="form-group">
                        <input type="number" min="0" class="form-control formBarang kuantitas" id="kuantitas` + i + `" name="kuantitas[]" placeholder="Kuantitas" required>
                    </div>
                    </div>
                    <div class="order-4 order-md-3 col-6 col-md-2">
                    <div class="form-group">
                        <input type="number" min="0" class="form-control formBarang" value="0" id="harga` + i + `" placeholder="Harga Satuan" readonly>
                    </div>
                    </div>
                    <div class="order-5 order-md-4 col-6 col-md-2">
                    <div class="form-group">
                        <input type="number" min="0" class="form-control formBarang subtotal" value="0" id="subtotal` +
                    i + `" placeholder="Subtotal" readonly>
                    </div>
                    </div>
                    <div class="order-3 order-md-5 col-4 col-md-1">
                    <button type="button" class="btn btn-danger w-100 btn_remove" id="button` + i + `">&times;</button>
                    </div>
                    </div>`);
            });

            $(document).on('change', '.namaBarang', function() {
                index = $(this).val().split(' ')[0]
                id = $(this).attr('id').match(/(\d+)/)[0]
                kuantitas = $('#kuantitas' + id + '').val()
                $('#harga' + id + '').val(harga[index])
                $('#subtotal' + id + '').val($('#harga' + id + '').val() * kuantitas)

                var total = parseInt(0)
                for (let i = 0; i < exist.length; i++) {
                    total += parseInt($('#subtotal' + exist[i] + '').val())
                }
                $('#totalTransaksi').val(total)
            })

            $(document).on('change', '.kuantitas', function() {
                kuantitas = $(this).val()
                id = $(this).attr('id').match(/(\d+)/)[0]
                $('#subtotal' + id + '').val($('#harga' + id + '').val() * kuantitas)

                var total = parseInt(0)
                for (let i = 0; i < exist.length; i++) {
                    total += parseInt($('#subtotal' + exist[i] + '').val())
                }
                $('#totalTransaksi').val(total)
            })



            $(document).on('click', '.btn_remove', function() {
                var button_id = $(this).attr("id").match(/(\d+)/)[0];
                exist = arrayRemove(exist, button_id)
                $('#row' + button_id + '').remove();
            });
        });
    </script>
@endpush

resources/views/transaksi/index.blade.php
@extends('layouts.master')

@section('title')
    Data Transaksi | Cashier
@endsection

@push('styles')
    <link href="vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush

@php
function tanggalFormat($date)
{
    $day = [1 => 'Senin', 'Selasa', 'Rabu', 'Kamis', "Jum'at", 'Sabtu', 'Minggu'];
    $month = [1 => 'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];

    $hari = $day[$date->format('N')];
    $tanggal = $date->format('d') . ' ' . $month[$date->format('n')] . ' ' . $date->format('Y');
    $jam = $date->format('H') . ':' . $date->format('i');

    return $hari . ', ' . $tanggal . ' ' . $jam;
}
@endphp

@section('content')
    <div class="d-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Data Transaksi</h1>
        <a href="{{ route('transaksi.create') }}" class="btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-cart-plus fa-sm text-white-50 d-inline-block"></i>
            <div class="d-none d-sm-inline-block">Tambah Transaksi</div>
        </a>
    </div>

    <div class="card shadow mb-4">
        <!-- Card Header - Accordion -->
        <a href="#filterCard" class="d-block card-header py-3" data-toggle="collapse" role="button">
            <h6 class="m-0 font-weight-bold text-primary">Filter Transaksi</h6>
        </a>
        <!-- Card Content - Collapse -->
        <div class="collapse show" id="filterCard">
            <div class="card-body">
                <form action="{{ route('transaksi.index') }}" method="get">
                    <div class="row">
                        <div class="col-md-6">
                            <h6 class="font-weight-bold text-primary">Berdasarkan Tanggal</h6>
                            <div class="form-group">
                                <input type="date" name="date" value="{{ request('date') }}" class="form-control">
                            </div>

                            <h6 class="font-weight-bold text-primary">Berdasarkan Total Harga</h6>
                            <div class="form-group">
                                <input type="number" name="min" min="0" value="{{ request('min') }}"
                                    class="form-control" placeholder="Harga Minimal">
                            </div>

                            <div class="form-group">
                                <input type="number" name="max" min="0" value="{{ request('max') }}"
                                    class="form-control" placeholder="Harga Maksimal">
                            </div>

                        </div>
                        <div class="col-md-6">
                            <h6 class="font-weight-bold text-primary">Berdasarkan Barang</h6>
                            <div id="filterBarang">
                                <div class="row" id="row1">
                                    <div class="col-10">
                                        <div class="form-group">
                                            <input class="form-control formBarang namaBarang" name="barang[]"
                                                list="nama_barang"
                                                value="{{ request('barang') != null ? request('barang')[0] : '' }}"
                                                onchange="resetIfInvalid(this);">
                                            <datalist id="nama_barang">
                                                @foreach ($barang as $item)
                                                    <option value="{{ $item->id }} - {{ $item->nama_barang }}">
                                                    </option>
                                                @endforeach
                                            </datalist>
                                        </div>
                                    </div>
                                    <div class="col-2">
                                        <button type="button" id="tambahField" class="btn btn-primary w-100 mb-3">&plus;
                                        </button>
                                    </div>
                                </div>

                                @if (request('barang') != null)
                                    @php
                                        $countBarang = count(request('barang'));
                                    @endphp

                                    @for ($i = 1; $i < $countBarang; $i++)
                                        <div class="row" id="row{{ $i + 1 }}">
                                            <div class="col-10">
                                                <div class="form-group">
                                                    <input class="form-control formBarang namaBarang" name="barang[]"
                                                        list="nama_barang" value="{{ request('barang')[$i] }}"
                                                        onchange="resetIfInvalid(this);">
                                                    <datalist id="nama_barang">
                                                        @foreach ($barang as $item)
                                                            <option
                                                                value="{{ $item->id }} - {{ $item->nama_barang }}">
                                                            </option>
                                                        @endforeach
                                                    </datalist>
                                                </div>
                                            </div>
                                            <div class="col-2">
                                                <button type="button" id="{{ $i + 1 }}"
                                                    class="btn btn-danger w-100 mb-3 kurangField">&minus;
                                                </button>
                                            </div>
                                        </div>
                                    @endfor
                                @else
                                    @php
                                        $countBarang = 1;
                                    @endphp
                                @endif
                            </div>
                        </div>
                        <button type="submit" class="btn btn-sm btn-primary w-100">Cari</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Data Transaksi</h6>
        </div>
        <div class="card-body">

            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr class="text-center">
                            <th>ID</th>
                            <th>Waktu Transaksi</th>
                            <th>Total Transaksi (Rp)</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr class="text-center">
                            <th>ID</th>
                            <th>Waktu Transaksi</th>
                            <th>Total Transaksi (Rp)</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach ($transaksi_pembelian as $item)
                            <tr>
                                <td class="text-center">{{ $item->id }}</td>
                                <td>{{ tanggalFormat($item->created_at) }}</td>
                                <td class="text-right">{{ number_format($item->total_harga, 0, ',', '.') }}</td>
                                <td class="text-center"><a
                                        href="{{ route('transaksi.show', ['transaksi' => $item->id]) }}"
                                        class="btn btn-sm btn-info">Detail</a></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <!-- Page level plugins -->
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script>
        // Call the dataTables jQuery plugin
        $(document).ready(function() {
            $('#dataTable').DataTable({
                columnDefs: [{
                    orderable: false,
                    targets: 1,
                }, {
                    orderable: false,
                    targets: 3
                }, {
                    type: "num-fmt",
                    targets: 2
                }]
            });
        });
    </script>

    <script>
        function resetIfInvalid(el) {
            //just for beeing sure that nothing is done if no value selected
            if (el.value == "")
                return;
            var options = el.list.options;
            for (var i = 0; i < options.length; i++) {
                if (el.value == options[i].value)
                    //option matches: work is done
                    return;
            }
            //no match was found: reset the value
            el.value = "";
        }
        var i = <?= $countBarang ?>

        $(document).ready(function() {
            $('#tambahField').on('click', function() {
                i++
                $('#filterBarang').append(`<div class="row" id="row` + i + `">
                                    <div class="col-10">
                                        <div class="form-group">
                                            <input class="form-control formBarang namaBarang" name="barang[]"
                                                list="nama_barang" onchange="resetIfInvalid(this);" required>
                                            <datalist id="nama_barang">
                                                @foreach ($barang as $item)
                                                    <option value="{{ $item->id }} - {{ $item->nama_barang }}">
                                                    </option>
                                                @endforeach
                                            </datalist>
                                        </div>
                                    </div>
                                    <div class="col-2">
                                        <button type="button" id="` + i + `"
                                            class="btn btn-danger w-100 mb-3 kurangField">&minus;</button>
                                    </div>
                                </div>`)
            })

            $(document).on('click', '.kurangField', function() {
                var id = $(this).attr('id')
                console.log()
                $('#row' + id + '').remove()
            })
        })
    </script>
@endpush

resources/views/transaksi/show.blade.php
@extends('layouts.master')

@section('title')
    Transaksi #{{ $id }} | Cashier
@endsection

@section('content')
    <div class="d-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Transaksi #{{ $id }}</h1>
        <a href="{{ route('transaksi.print', ['transaksi_id' => $id]) }}" class="btn btn-sm btn-danger shadow-sm"><i
                class="fas fa-download fa-sm text-white-50 d-inline-block"></i>
            <div class="d-none d-sm-inline-block">Unduh PDF</div>
        </a>
    </div>
    <div class="row">

    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Daftar Barang</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr class="text-center">
                            <th>No</th>
                            <th>Nama Barang</th>
                            <th>Kuantitas</th>
                            <th>Harga Satuan</th>
                            <th>Subtotal</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th colspan="4" class="text-center">Total Transaksi</th>
                            <th class="text-right"> Rp {{ number_format($total, 0, ',', '.') }}</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach ($transaksi as $key => $value)
                            <tr>
                                <td class="text-center">{{ $key + 1 }}</td>
                                <td>{{ $value->masterBarang->nama_barang }}</td>
                                <td class="text-center">{{ $value->jumlah }}</td>
                                <td class="text-right">{{ number_format($value->harga_satuan, 0, ',', '.') }}</td>
                                <td class="text-right">
                                    {{ number_format($value->jumlah * $value->harga_satuan, 0, ',', '.') }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection