routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MasterBarangController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\TransaksiPembelianController;
use App\Http\Controllers\PDFController;
use App\Models\TransaksiPembelian;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'home']);
Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
    Route::resource('transaksi', TransaksiPembelianController::class)->only(['store','show', 'create']);
    Route::middleware(['admin'])->group(function (){
        Route::resource('transaksi', TransaksiPembelianController::class)->only(['index']);
        Route::resource('barang', MasterBarangController::class)->except(['edit']);
        Route::resource('pengguna', PenggunaController::class)->except(['show', 'edit']);
    });
    Route::resource('pengguna', PenggunaController::class)->only(['show']);
    Route::get('transaksi/{transaksi_id}/printtransaksi', [PDFController::class, 'printTransaksi'])->name('transaksi.print');
});
require __DIR__ . '/auth.php';

app/Http/Controllers/PenggunaController.php
<?php

namespace App\Http\Controllers;

use Hash;
use App\Models\User;
use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;

class PenggunaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pengguna = User::all();
        return view('pengguna.index', ['pengguna'=> $pengguna]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pengguna.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'nama_pengguna' => 'required',
            'email' => 'required|unique:users,email',
            'password' => 'required|min:8',
            'role' => 'required'
        ]);

        $user = new User;
        $user->name = $request->nama_pengguna;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->is_admin = $request->role;
        $user->save();
        
        Alert::success('Berhasil', 'Pengguna baru dengan nama pengguna '.$user->name.' berhasil ditambahkan.');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show($id, User $user)
    {
        if(!auth()->user()->is_admin && auth()->user()->id != $id) {
            abort(403);
        } else {
            $pengguna = User::findOrFail($id);
            return view('pengguna.show', ['pengguna'=>$pengguna]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update($id, Request $request, User $user)
    {
        $validated = $request->validate([
            'nama_pengguna' => 'required',
            'role' => 'required'
        ]);

        $user = User::find($id);
        $user->name = $request->nama_pengguna;
        if($id == 1 && auth()->user()->id == 1) {
            if ($request->role != 1) {
                Alert::error('Gagal', 'Role admin kasir utama tidak dapat diubah.');
                return redirect()->back();
            } else {
                if($request->password != NULL) {
                    $user->password = Hash::make($request->password);
                }
                $user->save();
                Alert::success('Berhasil', 'Pengguna dengan nama pengguna '.$user->name.' berhasil diedit.');
                return redirect()->back();
            }
        } else {
            $user->is_admin = $request->role;
            if($request->password != NULL) {
                $user->password = Hash::make($request->password);
            }
            $user->save();
            Alert::success('Berhasil', 'Pengguna dengan nama pengguna '.$user->name.' berhasil diedit.');
            return redirect()->back();
        }       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, User $user)
    {
        if($id == 1) {
            Alert::error('Gagal', 'Admin Kasir Utama tidak dapat dihapus');
            return redirect()->back();
        } else {
            User::destroy($id);
            Alert::success('Berhasil', 'Pengguna berhasil dihapus');
            return redirect()->back();
        }
    }
}

resources/views/pengguna/create.blade.php
@extends('layouts.master')

@section('title')
    Tambah Pengguna | Cashier
@endsection

@section('content')
    <div class="d-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Pengguna</h1>
        <a href="{{ route('pengguna.index') }}" class="btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-list fa-sm text-white-50 d-inline-block"></i>
            <div class="d-none d-sm-inline-block">Data Pengguna</div>
        </a>
    </div>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Tambah Pengguna Baru</h6>
        </div>
        <div class="card-body">
            <form action="{{ route('pengguna.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="namaPengguna">Nama Pengguna</label>
                    <input type="text" name="nama_pengguna" class="form-control"
                        oninvalid="this.setCustomValidity('Nama Pengguna tidak boleh kosong')"
                        oninput="this.setCustomValidity('')" required>
                </div>
                <div class="form-group">
                    <label for="emailPengguna">Alamat Email</label>
                    <input type="email" name="email" class="form-control"
                        oninvalid="this.setCustomValidity('Email tidak boleh kosong')" oninput="this.setCustomValidity('')"
                        required>
                </div>
                <div class="form-group">
                    <label for="password">Kata Sandi</label>
                    <input type="text" name="password" minlength="8" class="form-control"
                        oninvalid="this.setCustomValidity('Password tidak boleh kosong')"
                        oninput="this.setCustomValidity('')" required>
                </div>
                <div class="form-group">
                    <label for="role">Role</label>
                    <select class="form-control" name="role" id="role" required>
                        <option value="0">Kasir</option>
                        <option value="1">Admin Kasir</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary w-100 mb-3">Tambah Pengguna Baru</button>
            </form>

        </div>
    </div>
@endsection

resources/views/pengguna/index.blade.php
@extends('layouts.master')

@section('title')
    Data Pengguna | Cashier
@endsection

@push('styles')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endpush


@section('content')
    <div class="d-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Data Pengguna</h1>
        <a href="{{ route('pengguna.create') }}" class="btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-plus fa-sm text-white-50 d-inline-block"></i>
            <div class="d-none d-sm-inline-block">Tambah Pengguna</div>
        </a>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Data Pengguna</h6>
        </div>
        <div class="card-body">

            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr class="text-center">
                            <th>ID</th>
                            <th>Nama Pengguna</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr class="text-center">
                            <th>ID</th>
                            <th>Nama Pengguna</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach ($pengguna as $item)
                            <tr>
                                <td class="text-center">{{ $item->id }}</td>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->email }}</td>
                                <td class="text-center">{{ $item->is_admin ? 'Admin Kasir' : 'Kasir' }}</td>
                                <td class="text-center text-nowrap">
                                    <a href="{{ route('pengguna.show', ['pengguna' => $item->id]) }}"
                                        class="btn btn-sm btn-info">Detail</a>
                                    <button type="button" class="btn btn-sm btn-outline-primary updatePengguna"
                                        data-toggle="modal" data-target="#updatePengguna" data-id="{{ $item->id }}"
                                        data-nama="{{ $item->name }}" data-email="{{ $item->email }}"
                                        data-role="{{ $item->is_admin }}"
                                        data-url="{{ route('pengguna.update', ['pengguna' => $item->id]) }}">
                                        Edit
                                    </button>
                                    <form action="{{ route('pengguna.update', ['pengguna' => $item->id]) }}"
                                        method="POST" class="d-inline">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('modal')
    <div class="modal fade" id="updatePengguna" tabindex="-1" aria-labelledby="updatePenggunaLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content shadow mb-4">
                <div class="card">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Form Update Pengguna</h6>
                    </div>
                    <div class="card-body">
                        <form id="formupdatePengguna" method="post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="namaPengguna">Nama Pengguna</label>
                                <input type="text" name="nama_pengguna" id="nama_pengguna" class="form-control"
                                    oninvalid="this.setCustomValidity('Nama Pengguna tidak boleh kosong')"
                                    oninput="this.setCustomValidity('')" required>
                            </div>
                            <div class="form-group">
                                <label for="emailPengguna">Alamat Email</label>
                                <input type="email" id="email" class="form-control"
                                    oninvalid="this.setCustomValidity('Email tidak boleh kosong')"
                                    oninput="this.setCustomValidity('')" disabled>
                            </div>
                            <div class="form-group">
                                <label for="password">Kata Sandi</label>
                                <input type="text" name="password" minlength="8" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="role">Role</label>
                                <select class="form-control" name="role" id="role" required>
                                    <option value="0">Kasir</option>
                                    <option value="1">Admin Kasir</option>
                                </select>
                            </div>
                            <hr>
                            <div class="text-right">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                                <button type="submit" class="btn btn-primary">Update Pengguna</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function() {
            $('.updatePengguna').on('click', function() {
                var id = $(this).attr('data-id')
                $('form#formupdatePengguna').attr('action', $(this).attr('data-url'))
                $('#nama_pengguna').val($(this).attr('data-nama'))
                $('#email').val($(this).attr('data-email'))
                $('#role').val($(this).attr('data-role'))
            })
        })
    </script>

    <!-- Page level plugins -->
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script>
        // Call the dataTables jQuery plugin
        $(document).ready(function() {
            $('#dataTable').DataTable({
                columnDefs: [{
                    orderable: false,
                    targets: 3
                }]
            });
        });
    </script>
@endpush

resources/views/pengguna/show.blade.php
@extends('layouts.master')

@section('title')
    {{ $pengguna->name }} | Cashier
@endsection

@push('styles')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endpush


@section('content')
    <div class="d-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Profil</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Profil Pengguna</h6>
        </div>
        <div class="card-body text-center">
            <img src="{{ asset('img/undraw_profile.svg') }}" class="img-profile rounded-circle" style="max-width: 200px">

            <h1>{{ $pengguna->name }}</h1>
            <p>Role : {{ $pengguna->is_admin ? 'Admin Kasir' : 'Kasir' }}</p>
            <p>Email : {{ $pengguna->email }}</p>
        </div>
    </div>
@endsection

@section('modal')
    <div class="modal fade" id="updatePengguna" tabindex="-1" aria-labelledby="updatePenggunaLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content shadow mb-4">
                <div class="card">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Form Update Pengguna</h6>
                    </div>
                    <div class="card-body">
                        <form id="formupdatePengguna" method="post">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="namaPengguna">Nama Pengguna</label>
                                <input type="text" name="nama_pengguna" id="nama_pengguna" class="form-control"
                                    oninvalid="this.setCustomValidity('Nama Pengguna tidak boleh kosong')"
                                    oninput="this.setCustomValidity('')" required>
                            </div>
                            <div class="form-group">
                                <label for="emailPengguna">Alamat Email</label>
                                <input type="email" name="email" id="email" class="form-control"
                                    oninvalid="this.setCustomValidity('Email tidak boleh kosong')"
                                    oninput="this.setCustomValidity('')" required>
                            </div>
                            <div class="form-group">
                                <label for="password">Kata Sandi</label>
                                <input type="text" name="password" minlength="8" class="form-control"
                                    oninvalid="this.setCustomValidity('Password tidak boleh kosong')"
                                    oninput="this.setCustomValidity('')" required>
                            </div>
                            <div class="form-group">
                                <label for="role">Role</label>
                                <select class="form-control" name="role" id="role" required>
                                    <option value="0">Kasir</option>
                                    <option value="1">Admin Kasir</option>
                                </select>
                            </div>
                            <hr>
                            <div class="text-right">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                                <button type="submit" class="btn btn-primary">Update Pengguna</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function() {
            $('.updatePengguna').on('click', function() {
                var id = $(this).attr('data-id')
                $('form#formupdatePengguna').attr('action', $(this).attr('data-url'))
                $('#nama_pengguna').val($(this).attr('data-nama'))
                $('#email').val($(this).attr('data-email'))
                $('#role').val($(this).attr('data-role'))
            })
        })
    </script>

    <!-- Page level plugins -->
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

    <!-- Page level custom scripts -->
    <script>
        // Call the dataTables jQuery plugin
        $(document).ready(function() {
            $('#dataTable').DataTable({
                columnDefs: [{
                    orderable: false,
                    targets: 3
                }]
            });
        });
    </script>
@endpush